/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{ type: "autogenerated", dirName: "." }],
  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
  */
  earlyCareerSidebar: [
    'early-career/intro',
    {
      type: 'category',
      label: '📚 Learning to Code',
      items: [
        'early-career/learning-to-code/self-learning-resources', 
        'early-career/learning-to-code/bootcamps'
      ],
    },
    {
      type: 'category',
      label: '🔎 Job Hunting',
      items: [
        'early-career/job-hunting/general-advice', 
        'early-career/job-hunting/job-boards', 
        'early-career/job-hunting/tracking', 
        'early-career/job-hunting/time-management'
      ],
    },
    {
      type: 'category',
      label: '👥 Community',
      items: [
        'early-career/community/personal-recs',
        'early-career/community/other-places'
      ],
    },
    {
      type: 'category',
      label: '📣 Marketing Yourself',
      items: [
        'early-career/marketing-yourself/telling-your-story',
        'early-career/marketing-yourself/resume-cover-letter',
        'early-career/marketing-yourself/github-linkedin',
        'early-career/marketing-yourself/portfolio-personal-website',
        'early-career/marketing-yourself/icing-on-the-cake'
      ],

    },
    {
      type: 'category',
      label: '💬 Job Interviews',
      items: [
        'early-career/job-interviews/interview-tips'
      ],
    },
    {
      type: 'category',
      label: '🤑 Negotiating',
      items: [
        'early-career/negotiating/understanding-market',
        'early-career/negotiating/how-to-negotiate'
      ],
    },
    {
      type: 'category',
      label: '💻 Starting a New Job',
      items: [
        'early-career/starting-new-job/onboarding-advice'
      ],
    },
  ],
  careerDevSidebar: [
    'career-dev/intro',
    {
      type: 'category',
      label: '1️⃣ 1-on-1s',
      items: [
        'career-dev/one-on-ones/effective-1-on-1s',
      ]
    }
  ]
};

module.exports = sidebars;
